title: Campus Care DTU
description: Retooling the Urban Belonging App to evaluate and create quali-quantitative insight into DTU Campus, Lyngby
theme: jekyll-theme-minimal

logo: main/Urban%20Belonging%20App%20pr%C3%A6sentation.jpg

