## title: <span style="font-family:Georgia,serif;color:#a42424;align=center">Campus Care DTU</span>
description: Retooling the Urban Belonging App to evaluate and create quali-quantitative insight into DTU Campus, Lyngby
theme: jekyll-theme-minimal

logo: images/MAIN-test.svg

