title: <span style="color:red">some **Campus Care DTU** text</span>
description: Retooling the Urban Belonging App to evaluate and create quali-quantitative insight into DTU Campus, Lyngby
theme: jekyll-theme-minimal

logo: images/MAIN-test.svg

